repos:
  
- repo: https://github.com/pre-commit/mirrors-isort
  rev: 'v5.9.3'  # Use the revision sha / tag you want to point at
  hooks:
  - id: isort

- repo: https://gitlab.com/pycqa/flake8
  rev: '3.9.2'  # Use the revision sha / tag you want to point at
  hooks:
  - id: flake8
    additional_dependencies: [flake8-docstrings]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 'v4.0.1'  # Use the revision sha / tag you want to point at
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
    exclude: backend/openapi.json
  - id: check-docstring-first
  - id: check-json
  - id: check-yaml
  - id: debug-statements
  - id: name-tests-test
    exclude: backend/tests/checker.py
    args:
    - --django
  - id: requirements-txt-fixer

